# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
        - task: TerraformInstaller@0
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure Pass - Sponsorship(0683d0f3-16e7-4c33-bb65-427c23da86aa)'
            backendAzureRmResourceGroupName: 'storage-rg'
            backendAzureRmStorageAccountName: 'pocdikshatfstate'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTaskV3@3
          inputs:
            provider: 'azurerm'
            command: 'validate'
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure Pass - Sponsorship(0683d0f3-16e7-4c33-bb65-427c23da86aa)'
              backendAzureRmResourceGroupName: 'storage-rg'
              backendAzureRmStorageAccountName: 'pocdikshatfstate'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Azure Pass - Sponsorship(0683d0f3-16e7-4c33-bb65-427c23da86aa)'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure Pass - Sponsorship(0683d0f3-16e7-4c33-bb65-427c23da86aa)'
        

